version: '3'
services:
  postgres:
    image: postgres:15.3
    restart: "unless-stopped"
    container_name: practice_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"